export default {
  id: "qoder-api",
  priority: 31,
  alias: "qda",
  uiAlias: "qda",
  display: {
    name: "Qoder API",
    icon: "water_drop",
    color: "#EC4899",
    textIcon: "QA",
    website: "https://qoder.com",
    notice: {
      text: "This provider uses a Personal Access Token. Account may be restricted or banned. Use at your own risk.",
      apiKeyUrl: "https://qoder.com/account/integrations",
    },
    deprecated: true,
    deprecationNotice: "RISK_NOTICE",
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api3.qoder.sh/algo/api/v2/service/pro/sse/agent_chat_generation",
    format: "openai",
    authType: "api_key",
    headers: {},
    timeoutMs: 120000,
    stallTimeoutMs: 90000,
  },
  models: [
    { id: "auto", name: "Auto-select by Qoder" },
    { id: "ultimate", name: "Highest tier" },
    { id: "performance", name: "Performance tier" },
    { id: "efficient", name: "Efficient tier" },
    { id: "lite", name: "Free tier" },
    { id: "qmodel_latest", name: "Qwen 3.7 Max" },
    { id: "qmodel", name: "Qwen 3.6 Plus" },
    { id: "dmodel", name: "DeepSeek V4 Pro" },
    { id: "dfmodel", name: "DeepSeek V4 Flash" },
    { id: "gm51model", name: "GLM 5.1" },
    { id: "kmodel", name: "Kimi K2.6" },
    { id: "mmodel", name: "MiniMax M2.7" },
  ],
  features: {
    usage: true,
    usageApikey: true,
  },
};
